str = input('다섯 문자 이상의 문자열 입력 >>')
print('입력 문자열: %s' %str)
print('입력 문자열의 길이: %d' %len(str))
print("첫 문자: %c" % str[:1])
print("마지막 문자: %c" % str[-1:])
print("첫문자를 제외한 부분 문자열: %s" % str[1:])
print("마지막 문자를 제외한 부분 문자열: %s" % str[:-1])
print("맨 앞과 뒤의 두 문자씩을 제외한 부분 문자열: %s" %str[1:-1])
print("역 문자열: %s" %str[::-1])
